apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: dc2c6xxcm-nodejs 
  janus-idp.io/tekton: dc2c6xxcm-nodejs
  backstage.io/kubernetes-id: dc2c6xxcm-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dc2c6xxcm-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml