apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dc2c6xxcm-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc2c6xxcm-nodejs 
  name: dc2c6xxcm-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: dc2c6xxcm-nodejs 
